### ISSUE TITLE
getPath method no longer exists on DirectDebitConfigProvider

### ISSUE THREAD

**Issue by JonasWijne** [MultiSafepay/magento2-core#28] opened 2024-05-23 15:24 UTC
https://github.com/MultiSafepay/magento2-core/blob/09771aa2f235d0414f856559907363c5915da8b2/Util/VaultUtil.php#L123

DirectDebitConfigProvider
https://github.com/MultiSafepay/magento2-core/blob/09771aa2f235d0414f856559907363c5915da8b2/Model/Ui/Gateway/DirectDebitConfigProvider.php#L20

parent
https://github.com/MultiSafepay/magento2-core/blob/09771aa2f235d0414f856559907363c5915da8b2/Model/Ui/GenericConfigProvider.php#L45

this can cause Magento to crash

**Comment by vinodsowdagar** [comment] 2024-05-23 15:42
Hi @JonasWijne ,

Thank you for the report. 

The issue is clear and we have added a task to the backlog to fix it. It will be included in the next release.
We will keep you informed in the meantime.

**Comment by vinodsowdagar** [comment] 2024-07-08 13:06
Hi @JonasWijne ,

We've released a new version where this fix has been included: https://github.com/MultiSafepay/magento2/releases/tag/3.7.0
I'm closing this issue for now. If you have any other questions, feel free to leave a comment or create a new issue.

**Closed as completed by vinodsowdagar** 2024-07-08 13:06 UTC
