### ISSUE TITLE
Manually invoicing incomplete order.

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2-core#13] opened 2022-02-10 15:33 UTC
I'm experiencing the following scenario.

Customer places order through Magento PWA checkout selecting creditcard as a payment method.
Customer arrives on MSP creditcard page, but doesn't fill out the creditcard form.
This causes the order to exist in Magento but not in MSP.

Shop owner now decides to manually invoice the order (customer paid in some other way).
If you do "Not Capture" the invoice the order is stuck on pending payment. And trying to capture the invoice throws an error, because the module tries to call the MSP api where the order does not exist.
If you "Capture Offline" the invoice gets generated and captured. But the order is stuck on Pending Payment and when you create a shipment you get an error because the module tries to call the MSP api where the order does not exist. After the shipment is created the order is still stuck on pending payment.
If you "Capture Online" the invoice creating fails because the module tries to call the MSP api where the order does not exist.

**Comment by vinodsowdagar** [comment] 2022-02-11 08:41
Hi @Hexmage ,

Thank you for reporting this. 
I have planned an investigation for this issue and am going to try to reproduce this and find a solution when possible.

I will keep you updated later.

**Comment by vinodsowdagar** [comment] 2022-02-14 11:29
Hi @Hexmage ,

We are looking into why the order is not going to processing when an invoice has been manually created.

In the meantime, if this happens again, I am suggesting for now to use the 'reorder' button to create a new order with the actual payment method the customer used (Bank transfer, check/money order, etc).

**Comment by Hexmage** [comment] 2022-04-06 12:21
@Vinod-MultiSafepay Do you have a status update on this issue?

**Comment by vinodsowdagar** [comment] 2022-04-06 13:23
Hi @Hexmage ,

We have a fix ready and are expecting to do a new release next week where it will become available.
As soon as the release has been done, i will let you know.

**Comment by vinodsowdagar** [comment] 2022-05-04 15:28
Hi @Hexmage ,

We had to delay the release, because of issues with the latest version of Magento. But this should be fixed in the latest version we have just released: https://github.com/MultiSafepay/magento2/releases/tag/2.17.0

I am closing this for now. If you still encounter problems or have questions, feel free to reopen the issue.

**Closed as completed by vinodsowdagar** 2022-05-04 15:28 UTC
